# Custom Language File for Launcher Customizer

[ejs.app]
title = "발찌 놀이터"

[ejs.landing]
mediaGitHubURL = "https://github.com/anzuseon/zzibal_Island"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "http://rebootms.kro.kr"

[ejs.settings]
sourceGithubLink = "https://github.com/anzuseon/zzibal_Island"
supportLink = "https://github.com/anzuseon/zzibal_Island/issues"

[ejs.welcome]
welcomeHeader = "발찌 놀이터에 오신 것을 환영합니다."
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
